/*
 * IntArrayModifier.java
 *
 * Created on October 23, 2008, 12:43 PM
 */
package draw;

import util.GetAndSetMethodHolder;

/**
 *
 * @author  nyffeldd
 */
public class BooleanModifier extends javax.swing.JPanel {

    GetAndSetMethodHolder methods;

    /** Creates new form IntArrayModifier */
    public BooleanModifier(GetAndSetMethodHolder methods) {
        initComponents();
        this.methods = methods;
        updateGui();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrayPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        arrayPanel.setLayout(new java.awt.BorderLayout());

        jToggleButton1.setText("Press To Change");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);

        arrayPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(arrayPanel, java.awt.BorderLayout.CENTER);
        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        methods.set(jToggleButton1.isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrayPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    private void updateGui() {
        jToggleButton1.setSelected(Boolean.parseBoolean("" + methods.get()));
    }
}
