/*
 * ColorModifier.java
 *
 * Created on October 24, 2008, 12:37 PM
 */

package draw;

import util.Color;

/**
 *
 * @author  nyffeldd
 */
public class ColorModifier extends javax.swing.JPanel {
    Color [] colors = new Color[1];
    /** Creates new form ColorModifier */
    public ColorModifier(Color c) {
        initComponents();
        colors[0] = c;
        jColorChooser1.setColor(c.getColor());
        alphaSpinner.setValue(255);
    }
    
    public ColorModifier(Color [] c) {
        initComponents();
        colors = c;
        jColorChooser1.setColor(c[0].getColor());
        alphaSpinner.setValue(255);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        alphaSpinner = new javax.swing.JSpinner();

        setLayout(new java.awt.BorderLayout());

        jPanel1.add(jColorChooser1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jLabel8.setText("Opacity:");
        jPanel2.add(jLabel8);

        alphaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaSpinnerStateChanged(evt);
            }
        });
        jPanel2.add(alphaSpinner);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void alphaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSpinnerStateChanged
        int a = Integer.parseInt(alphaSpinner.getValue() + "");
        if (a > 255) {
            a = 255;
            alphaSpinner.setValue(new Integer(a));
        }
        if (a < 0) {
            a = 0;
            alphaSpinner.setValue(new Integer(a));
        }
    }//GEN-LAST:event_alphaSpinnerStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int i = 0; i < colors.length; i++)
        {
            colors[i].setColor(jColorChooser1.getColor());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner alphaSpinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
}
