/*
 * ColorArraySetUp.java
 *
 * Created on April 9, 2007, 4:14 PM
 */
package draw;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.StringTokenizer;
import javax.swing.JLabel;
import util.ColorArray;
import util.ColorArrayFactory;
import util.DFactory;
import util.GetAndSetMethodHolder;
import java.io.*;

/**
 *m,246,196,84,255
 * @author  doubleD
 */
public class ColorArraySetUp extends javax.swing.JPanel {

    public static final String DIRECTORY = "x/ColorArrays/";
    ColorArray colors;
    String context = "";
    int selectedIndex = 0;
    GetAndSetMethodHolder methods;

    public ColorArraySetUp(GetAndSetMethodHolder m) {
        this((ColorArray) m.get());
        methods = m;
    }

    /** Creates new form ColorArraySetUp */
    public ColorArraySetUp(ColorArray c) {
        initComponents();
        colors = c;
        updateColorChooser(selectedIndex);
        initLabels();
        util.Color color = c.get(7);
        jColorChooser1.setColor(color.getColor());
        alphaSpinner.setValue(color.getAlpha());
        sizeSpinner.setValue(c.getSize());
        float [] temp = util.Color.RGBtoHSB(color.getRed(), color.getGreen(), color.getBlue(), null);
        hSpinner.setValue((int) (temp[0] * 360));
        sSpinner.setValue((int) (temp[1] * 100));
        bSpinner.setValue((int) (temp[2] * 100));
        typeBox.setModel(new javax.swing.DefaultComboBoxModel(ColorArrayFactory.types));
        typeBox.setSelectedItem("m");
    }

    public ColorArraySetUp(ColorArray c, String context) {
        this(c);
        this.context = context;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panel0 = new javax.swing.JPanel();
        label0 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        panel8 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        panel9 = new javax.swing.JPanel();
        label9 = new javax.swing.JLabel();
        panel10 = new javax.swing.JPanel();
        label10 = new javax.swing.JLabel();
        panel11 = new javax.swing.JPanel();
        label11 = new javax.swing.JLabel();
        panel12 = new javax.swing.JPanel();
        label12 = new javax.swing.JLabel();
        panel13 = new javax.swing.JPanel();
        label13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        sizeSpinner = new javax.swing.JSpinner();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        sSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        bSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        hSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        bSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        sSpinner1 = new javax.swing.JSpinner();
        previewPanel = new javax.swing.JPanel();
        prevPan1 = new javax.swing.JPanel();
        prevPan2 = new javax.swing.JPanel();
        prevPan3 = new javax.swing.JPanel();
        prevPan4 = new javax.swing.JPanel();
        prevPan5 = new javax.swing.JPanel();
        jFrame2 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel4 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        frame3Panel = new javax.swing.JPanel();
        jFrame4 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        savePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        colorArrayPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        alphaSpinner = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        typeBox = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 2, 0));

        panel0.setBackground(new java.awt.Color(255, 204, 204));

        label0.setText("NEG_GREY_7");
        label0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label0MouseClicked(evt);
            }
        });
        panel0.add(label0);

        jPanel1.add(panel0);

        panel1.setBackground(new java.awt.Color(255, 204, 204));

        label1.setText("NEG_GREY_6");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });
        panel1.add(label1);

        jPanel1.add(panel1);

        panel2.setBackground(new java.awt.Color(255, 204, 204));

        label2.setText("NEG_GREY_5");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });
        panel2.add(label2);

        jPanel1.add(panel2);

        panel3.setBackground(new java.awt.Color(255, 204, 204));

        label3.setText("NEG_GREY_4");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });
        panel3.add(label3);

        jPanel1.add(panel3);

        panel4.setBackground(new java.awt.Color(255, 204, 204));

        label4.setText("NEG_GREY_3");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });
        panel4.add(label4);

        jPanel1.add(panel4);

        panel5.setBackground(new java.awt.Color(255, 204, 204));

        label5.setText("NEG_GREY_2");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });
        panel5.add(label5);

        jPanel1.add(panel5);

        panel6.setBackground(new java.awt.Color(255, 204, 204));

        label6.setText("NEG_GREY_1");
        label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6MouseClicked(evt);
            }
        });
        panel6.add(label6);

        jPanel1.add(panel6);

        panel7.setBackground(new java.awt.Color(255, 204, 204));

        label7.setText("GREY");
        label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7MouseClicked(evt);
            }
        });
        panel7.add(label7);

        jPanel1.add(panel7);

        panel8.setBackground(new java.awt.Color(255, 204, 204));

        label8.setText("GREY_1");
        label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8MouseClicked(evt);
            }
        });
        panel8.add(label8);

        jPanel1.add(panel8);

        panel9.setBackground(new java.awt.Color(255, 204, 204));

        label9.setText("GREY_2");
        label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label9MouseClicked(evt);
            }
        });
        panel9.add(label9);

        jPanel1.add(panel9);

        panel10.setBackground(new java.awt.Color(255, 204, 204));

        label10.setText("GREY_3");
        label10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label10MouseClicked(evt);
            }
        });
        panel10.add(label10);

        jPanel1.add(panel10);

        panel11.setBackground(new java.awt.Color(255, 204, 204));

        label11.setText("GREY_4");
        label11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label11MouseClicked(evt);
            }
        });
        panel11.add(label11);

        jPanel1.add(panel11);

        panel12.setBackground(new java.awt.Color(255, 204, 204));

        label12.setText("GREY_5");
        label12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label12MouseClicked(evt);
            }
        });
        panel12.add(label12);

        jPanel1.add(panel12);

        panel13.setBackground(new java.awt.Color(255, 204, 204));

        label13.setText("GREY_6");
        label13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label13MouseClicked(evt);
            }
        });
        panel13.add(label13);

        jPanel1.add(panel13);

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Update Color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Size:");

        sizeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeSpinnerStateChanged(evt);
            }
        });

        jButton10.setText("Update Array");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hue:");

        hSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hSpinnerStateChanged(evt);
            }
        });

        jLabel2.setText("Sat:");

        sSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sSpinnerStateChanged(evt);
            }
        });

        jLabel3.setText("Bri:");

        bSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bSpinnerStateChanged(evt);
            }
        });

        jLabel4.setText("Hue:");

        hSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hSpinner1StateChanged(evt);
            }
        });

        jLabel6.setText("Bri:");

        bSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bSpinner1StateChanged(evt);
            }
        });

        jLabel7.setText("Sat:");

        sSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sSpinner1StateChanged(evt);
            }
        });

        previewPanel.setLayout(new java.awt.GridLayout(0, 1));

        prevPan1.setLayout(new java.awt.GridLayout(1, 0));
        previewPanel.add(prevPan1);

        prevPan2.setLayout(new java.awt.GridLayout(1, 0));
        previewPanel.add(prevPan2);

        prevPan3.setLayout(new java.awt.GridLayout(1, 0));
        previewPanel.add(prevPan3);

        prevPan4.setLayout(new java.awt.GridLayout(1, 0));
        previewPanel.add(prevPan4);

        prevPan5.setLayout(new java.awt.GridLayout(1, 0));
        previewPanel.add(prevPan5);

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, previewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jFrame1Layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sizeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 90, Short.MAX_VALUE)
                        .add(jButton10))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jFrame1Layout.createSequentialGroup()
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jFrame1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(hSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(jFrame1Layout.createSequentialGroup()
                                    .add(jLabel3)
                                    .add(11, 11, 11)
                                    .add(bSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jFrame1Layout.createSequentialGroup()
                                    .add(jLabel2)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(sSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 99, Short.MAX_VALUE)
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel7)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(hSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(sSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(sizeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jFrame1Layout.createSequentialGroup()
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(hSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(sSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(bSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3)))
                    .add(jFrame1Layout.createSequentialGroup()
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(hSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(sSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(bSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(previewPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFrame2.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame2WindowLostFocus(evt);
            }
        });

        jColorChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jColorChooser1MouseReleased(evt);
            }
        });
        jFrame2.getContentPane().add(jColorChooser1, java.awt.BorderLayout.CENTER);

        jButton15.setText("Update");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15);

        jFrame2.getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        jFrame3.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                jFrame3WindowLostFocus(evt);
            }
        });

        frame3Panel.setLayout(new java.awt.BorderLayout());
        jFrame3.getContentPane().add(frame3Panel, java.awt.BorderLayout.CENTER);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        jLabel9.setText("Name Your File");
        savePanel.add(jLabel9);

        jTextField2.setColumns(50);
        jTextField2.setText("FileName");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        savePanel.add(jTextField2);

        jButton14.setText("Save");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        savePanel.add(jButton14);

        jFrame4.getContentPane().add(savePanel, java.awt.BorderLayout.PAGE_START);

        setLayout(new java.awt.BorderLayout());

        colorArrayPanel.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(colorArrayPanel);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jButton8.setText("pri");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8);

        jButton7.setText("sec");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);

        jButton6.setText("ter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6);

        jButton4.setText("accPri");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);

        jButton5.setText("accSec");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5);

        jButton3.setText("accTer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);

        jPanel2.add(jPanel9);

        jToggleButton1.setText("set Stored Array");
        jPanel10.add(jToggleButton1);

        jButton12.setText("Save");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton12);

        jButton13.setText("Load");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);

        jPanel2.add(jPanel10);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        jButton9.setText("set cycling");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 111, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 51, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel5);

        jLabel8.setText("Opacity:");
        jPanel6.add(jLabel8);

        alphaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaSpinnerStateChanged(evt);
            }
        });
        jPanel6.add(alphaSpinner);

        jPanel8.add(jPanel6);

        jButton11.setText("Select Color");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);

        jPanel8.add(jPanel7);

        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(typeBox);

        jTextField1.setText("999");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel8.add(jTextField1);

        jButton2.setText("Update Array");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);

        jPanel3.add(jPanel8);

        add(jPanel3, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        changeColor();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void sizeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeSpinnerStateChanged
        resetPreview();
    }//GEN-LAST:event_sizeSpinnerStateChanged

    private void sSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sSpinner1StateChanged
        resetPreview();
    }//GEN-LAST:event_sSpinner1StateChanged

    private void bSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bSpinner1StateChanged
        resetPreview();
    }//GEN-LAST:event_bSpinner1StateChanged

    private void hSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hSpinner1StateChanged
        resetPreview();
    }//GEN-LAST:event_hSpinner1StateChanged

    private void bSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bSpinnerStateChanged
        resetPreview();
    }//GEN-LAST:event_bSpinnerStateChanged

    private void sSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sSpinnerStateChanged
        resetPreview();
    }//GEN-LAST:event_sSpinnerStateChanged

    private void hSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hSpinnerStateChanged
        resetPreview();
    }//GEN-LAST:event_hSpinnerStateChanged

    private void resetPreview() {
        previewPanel.setVisible(false);
        prevPan1.removeAll();
        prevPan2.removeAll();
        prevPan3.removeAll();
        prevPan4.removeAll();
        prevPan5.removeAll();

        ColorArray temp = ColorArrayFactory.getCyclingColorArray(typeBox.getSelectedItem() + "",
                Integer.parseInt(sizeSpinner.getValue() + ""),
                Integer.parseInt("" + hSpinner1.getValue()),
                Integer.parseInt("" + hSpinner.getValue()),
                Integer.parseInt("" + sSpinner1.getValue()),
                Integer.parseInt("" + sSpinner.getValue()),
                Integer.parseInt("" + bSpinner1.getValue()),
                Integer.parseInt("" + bSpinner.getValue()),
                Integer.parseInt(alphaSpinner.getValue() + ""));

        for (int i = 0; i < Integer.parseInt(sizeSpinner.getValue() + ""); i++) {
            temp.setStep(i);


            JLabel tempLab1 = new JLabel("");
            tempLab1.setOpaque(true);
            tempLab1.setBackground(temp.get(5).getColor());

            prevPan1.add(tempLab1);

            JLabel tempLab2 = new JLabel("");
            tempLab2.setOpaque(true);
            tempLab2.setBackground(temp.get(6).getColor());

            prevPan2.add(tempLab2);

            JLabel tempLab3 = new JLabel("");
            tempLab3.setOpaque(true);
            tempLab3.setBackground(temp.get(7).getColor());

            prevPan3.add(tempLab3);

            JLabel tempLab4 = new JLabel("");
            tempLab4.setOpaque(true);
            tempLab4.setBackground(temp.get(8).getColor());

            prevPan4.add(tempLab4);

            JLabel tempLab5 = new JLabel("");
            tempLab5.setOpaque(true);
            tempLab5.setBackground(temp.get(9).getColor());

            prevPan5.add(tempLab5);
        }

        previewPanel.setVisible(true);
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        colors.setArray(ColorArrayFactory.getCyclingColorArray(typeBox.getSelectedItem() + "",
                Integer.parseInt(sizeSpinner.getValue() + ""),
                Integer.parseInt("" + hSpinner1.getValue()),
                Integer.parseInt("" + hSpinner.getValue()),
                Integer.parseInt("" + sSpinner1.getValue()),
                Integer.parseInt("" + sSpinner.getValue()),
                Integer.parseInt("" + bSpinner1.getValue()),
                Integer.parseInt("" + bSpinner.getValue()),
                Integer.parseInt(alphaSpinner.getValue() + "")));


        resetPanels();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Main.moveTo.setSelected(true);
        jFrame1.setLocation(Main.DEFAULT_X_VALUE, 400);
        jFrame1.pack();
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void alphaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSpinnerStateChanged

        int a = Integer.parseInt(alphaSpinner.getValue() + "");
        if (a > 255) {
            a = 255;
            alphaSpinner.setValue(new Integer(a));
        }
        if (a < 0) {
            a = 0;
            alphaSpinner.setValue(new Integer(a));
        }
        colors.setAlpha(a);
        resetPanels();
        try {
            Main.show = true;
        } catch (Exception e) {
        }
        try {
            Main.moveTo.setSelected(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_alphaSpinnerStateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (!jToggleButton1.isSelected()) {
            colors.setArray(DFactory.primaryArray.getNewColorArray());
            resetPanels();
            try {
                Main.show = true;
            } catch (Exception e) {
            }
            try {
                Main.moveTo.setSelected(false);
            } catch (Exception e) {
            }
        } else {
            DFactory.primaryArray = colors.getNewColorArray();
            jToggleButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (!jToggleButton1.isSelected()) {
            colors.setArray(DFactory.secondaryArray.getNewColorArray());
            resetPanels();
            try {
                Main.show = true;
            } catch (Exception e) {
            }
            try {
                Main.moveTo.setSelected(false);
            } catch (Exception e) {
            }
        } else {
            DFactory.secondaryArray = colors.getNewColorArray();
            jToggleButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (!jToggleButton1.isSelected()) {
            colors.setArray(DFactory.tercaryArray.getNewColorArray());
            resetPanels();
            try {
                Main.show = true;
            } catch (Exception e) {
            }
            try {
                Main.moveTo.setSelected(false);
            } catch (Exception e) {
            }
        } else {
            DFactory.tercaryArray = colors.getNewColorArray();
            jToggleButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!jToggleButton1.isSelected()) {
            colors.setArray(DFactory.accPrimaryArray.getNewColorArray());
            resetPanels();
            try {
                Main.show = true;
            } catch (Exception e) {
            }
            try {
                Main.moveTo.setSelected(false);
            } catch (Exception e) {
            }
        } else {
            DFactory.accPrimaryArray = colors.getNewColorArray();
            jToggleButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!jToggleButton1.isSelected()) {
            colors.setArray(DFactory.accSecondaryArray.getNewColorArray());
            resetPanels();
            try {
                Main.show = true;
            } catch (Exception e) {
            }
            try {
                Main.moveTo.setSelected(false);
            } catch (Exception e) {
            }
        } else {
            DFactory.accSecondaryArray = colors.getNewColorArray();
            jToggleButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!jToggleButton1.isSelected()) {
            colors.setArray(DFactory.accTercaryArray.getNewColorArray());
            resetPanels();
            try {
                Main.show = true;
            } catch (Exception e) {
            }
            try {
                Main.moveTo.setSelected(false);
            } catch (Exception e) {
            }
        } else {
            DFactory.accTercaryArray = colors.getNewColorArray();
            jToggleButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void label0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label0MouseClicked
        unselectCurrentLabel();
        selectedIndex = 0;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label0MouseClicked

    private void jColorChooser1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColorChooser1MouseReleased
        if (evt.getButton() == evt.BUTTON1) {
            setField("c");
        } else {
            setField("m");
        }
    }//GEN-LAST:event_jColorChooser1MouseReleased

    private void setField(String s) {
        Color c = jColorChooser1.getColor();
        jTextField1.setText(s + "," + c.getRed() + "," + c.getGreen() + "," + c.getBlue() + "," + alphaSpinner.getValue());
        jTextField1.repaint();
    }

    private void label13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label13MouseClicked
        unselectCurrentLabel();
        selectedIndex = 13;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label13MouseClicked

    private void label12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label12MouseClicked
        unselectCurrentLabel();
        selectedIndex = 12;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label12MouseClicked

    private void label11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label11MouseClicked
        unselectCurrentLabel();
        selectedIndex = 11;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label11MouseClicked

    private void label10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label10MouseClicked
        unselectCurrentLabel();
        selectedIndex = 10;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label10MouseClicked

    private void label9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label9MouseClicked
        unselectCurrentLabel();
        selectedIndex = 9;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label9MouseClicked

    private void label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseClicked
        unselectCurrentLabel();
        selectedIndex = 8;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label8MouseClicked

    private void label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseClicked
        unselectCurrentLabel();
        selectedIndex = 7;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label7MouseClicked

    private void label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseClicked
        unselectCurrentLabel();
        selectedIndex = 6;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label6MouseClicked

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        unselectCurrentLabel();
        selectedIndex = 5;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label5MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        unselectCurrentLabel();
        selectedIndex = 4;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label4MouseClicked

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        unselectCurrentLabel();
        selectedIndex = 3;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label3MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        unselectCurrentLabel();
        selectedIndex = 2;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label2MouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        unselectCurrentLabel();
        selectedIndex = 1;
        selectLabel(selectedIndex);
    }//GEN-LAST:event_label1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setField(typeBox.getSelectedItem() + "");

        ColorArray temp = util.ColorArrayFactory.getArray(jTextField1.getText());
        colors.setArray(temp);

        resetPanels();
        try {
            Main.show = true;
            Main.moveTo.setSelected(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        colors.set(selectedIndex, jColorChooser1.getColor());
        resetPanels();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Main.moveTo.setSelected(true);
        jFrame2.setLocation(1600, 600);
        jFrame2.pack();
        jFrame2.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jFrame3WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame3WindowLostFocus
        jFrame3.setVisible(false);
        resetPanels();
    }//GEN-LAST:event_jFrame3WindowLostFocus

    private void jFrame2WindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame2WindowLostFocus
        jFrame2.setVisible(false);
    }//GEN-LAST:event_jFrame2WindowLostFocus

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        //Save
        savePanel.setVisible(true);
        jFileChooser1.setVisible(false);
        Main.moveTo.setSelected(true);
        jFrame4.pack();
        jFrame4.setLocation(1600, 20);
        jFrame4.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        //Load
        savePanel.setVisible(false);
        File file = new File(DIRECTORY);
        jFileChooser1.setCurrentDirectory(file);
        jFileChooser1.setVisible(true);
        Main.moveTo.setSelected(true);
        jFrame4.pack();
        jFrame4.setLocation(1600, 20);
        jFrame4.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if (evt.getActionCommand().equalsIgnoreCase("CancelSelection")) {
            jFrame4.setVisible(false);
        } else if (evt.getActionCommand().equalsIgnoreCase("ApproveSelection")) {
            try {
                FileInputStream f = new FileInputStream(jFileChooser1.getSelectedFile());
                ObjectInputStream s = new ObjectInputStream(f);
                ColorArray temp = (ColorArray) s.readObject();
                s.close();

                jFrame4.setVisible(false);
                colors.setArray(temp);
                resetPanels();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        save();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        save();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        setField(typeBox.getSelectedItem() + "");

        ColorArray temp = util.ColorArrayFactory.getArray(jTextField1.getText());
        colors.setArray(temp);

        resetPanels();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void save() {
        try {
            File file = new File(DIRECTORY + jTextField2.getText() + ".ser");
            file.createNewFile();
            FileOutputStream f = new FileOutputStream(file);
            ObjectOutputStream s = new ObjectOutputStream(f);
            s.writeObject(colors);
            s.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        jFrame4.setVisible(false);
    }

    private void updateColorChooser(int index) {
        jColorChooser1.setColor(colors.get(index).getColor());
    }

    private void initLabels() {
        labels[0] = label0;
        labels[1] = label1;
        labels[2] = label2;
        labels[3] = label3;
        labels[4] = label4;
        labels[5] = label5;
        labels[6] = label6;
        labels[7] = label7;
        labels[8] = label8;
        labels[9] = label9;
        labels[10] = label10;
        labels[11] = label11;
        labels[12] = label12;
        labels[13] = label13;

        panels[0] = panel0;
        panels[1] = panel1;
        panels[2] = panel2;
        panels[3] = panel3;
        panels[4] = panel4;
        panels[5] = panel5;
        panels[6] = panel6;
        panels[7] = panel7;
        panels[8] = panel8;
        panels[9] = panel9;
        panels[10] = panel10;
        panels[11] = panel11;
        panels[12] = panel12;
        panels[13] = panel13;

        resetPanels();
    }

    private void resetPanels() {
//        for (int i = 0; i < colors.getLength(); i++) {
//            panels[i].setBackground(colors.get(i).getColor());
//        }
        colorArrayPanel.setVisible(false);
        colorArrayPanel.removeAll();
        javax.swing.JPanel temp1 = new javax.swing.JPanel();
        temp1.setLayout(new java.awt.GridLayout(0, 1));
        for (int i = 0; i < colors.getLength(); i++) {
            ColorPanel cp = new ColorPanel(colors.getColorsAt(i), i);
            cp.addMouseListener(new java.awt.event.MouseAdapter() {

                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    formMouseReleased(evt);
                }
            });
            temp1.add(cp);
        }
        colorArrayPanel.add(temp1);

        for (int index = 0; index < colors.getSize(); index++) {
            javax.swing.JPanel temp = new javax.swing.JPanel();
            temp.setLayout(new java.awt.GridLayout(0, 1));
            for (int i = 0; i < colors.getLength(); i++) {
                ColorPanel cp = new ColorPanel(colors.getColorAt(index, i));
                cp.addMouseListener(new java.awt.event.MouseAdapter() {

                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        formMouseReleased(evt);
                    }
                });
                temp.add(cp);
            }

            colorArrayPanel.add(temp);
        }
        colorArrayPanel.setVisible(true);
    }

    private void formMouseReleased(MouseEvent evt) {
        ColorPanel cp = (ColorPanel) evt.getSource();
        ColorModifier cm = new ColorModifier(cp.colors);
        jColorChooser1.setColor(cp.colors[0].getColor());
        Main.moveTo.setSelected(true);
        frame3Panel.removeAll();
        frame3Panel.add(cm);
        jFrame3.pack();
        jFrame3.setLocation(1600, 400);
        jFrame3.setVisible(true);
    }

    private void unselectCurrentLabel() {
        labels[selectedIndex].setForeground(new Color(0, 0, 0, 255));
    }

    private void selectLabel(int i) {
        labels[i].setForeground(new Color(255, 255, 255, 255));
        updateColorChooser(i);
    }

    private void changeColor() {
        try {
            if (jTextField1.getText().indexOf(",") != -1) {
                StringTokenizer tok = new StringTokenizer(jTextField1.getText(), ",");
                tok.nextToken();
                int red = Integer.valueOf(tok.nextToken()).intValue();
                int green = Integer.valueOf(tok.nextToken()).intValue();
                int blue = Integer.valueOf(tok.nextToken()).intValue();

                jColorChooser1.setColor(red, green, blue);
            }
        } catch (Exception e) {

        }

    }
    javax.swing.JLabel[] labels = new javax.swing.JLabel[14];
    javax.swing.JPanel[] panels = new javax.swing.JPanel[14];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner alphaSpinner;
    private javax.swing.JSpinner bSpinner;
    private javax.swing.JSpinner bSpinner1;
    private javax.swing.JPanel colorArrayPanel;
    private javax.swing.JPanel frame3Panel;
    private javax.swing.JSpinner hSpinner;
    private javax.swing.JSpinner hSpinner1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JPanel panel0;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel10;
    private javax.swing.JPanel panel11;
    private javax.swing.JPanel panel12;
    private javax.swing.JPanel panel13;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel8;
    private javax.swing.JPanel panel9;
    private javax.swing.JPanel prevPan1;
    private javax.swing.JPanel prevPan2;
    private javax.swing.JPanel prevPan3;
    private javax.swing.JPanel prevPan4;
    private javax.swing.JPanel prevPan5;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JSpinner sSpinner;
    private javax.swing.JSpinner sSpinner1;
    private javax.swing.JPanel savePanel;
    private javax.swing.JSpinner sizeSpinner;
    private javax.swing.JComboBox typeBox;
    // End of variables declaration//GEN-END:variables
}
