/*
 * IntArrayModifier.java
 *
 * Created on October 23, 2008, 12:43 PM
 */

package draw;

import java.util.ArrayList;
import java.util.StringTokenizer;
import util.GetAndSetMethodHolder;

/**
 *
 * @author  nyffeldd
 */
public class IntArrayModifier extends javax.swing.JPanel {
    GetAndSetMethodHolder methods;
    
    /** Creates new form IntArrayModifier */
    public IntArrayModifier(GetAndSetMethodHolder methods) {
        initComponents();
        this.methods = methods;
        updateGui((int []) methods.get());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        arrayPanel.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        arrayPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(arrayPanel, java.awt.BorderLayout.CENTER);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringTokenizer tok = new StringTokenizer(jTextArea1.getText(), ", ");
        ArrayList temp = new ArrayList();
        
        while(tok.hasMoreTokens())
        {
            temp.add(Integer.valueOf(tok.nextToken()));
        }
        int [] temp2 = new int [temp.size()];

        for(int i = 0; i < temp.size(); i++)
        {
            temp2[i] = ((Integer)temp.get(i)).intValue();
        }
        
        methods.set(temp2);

    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void updateGui(int [] array) {
        String s = "" + array[0];
        
        for(int i = 1; i < array.length; i++)
        {
            s += "," + array[i];
        }
        jTextArea1.setText(s);
    }
    
}
