/*
 * IntArrayModifier.java
 *
 * Created on October 23, 2008, 12:43 PM
 */
package draw;

import util.GetAndSetMethodHolder;

/**
 *
 * @author  nyffeldd
 */
public class IntModifier extends javax.swing.JPanel {

    GetAndSetMethodHolder methods;

    /** Creates new form IntArrayModifier */
    public IntModifier(GetAndSetMethodHolder methods) {
        initComponents();
        this.methods = methods;
        updateGui(Integer.parseInt(methods.get() + ""));
        jTextField1.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrayPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        arrayPanel.setLayout(new java.awt.BorderLayout());

        jTextField1.setColumns(5);
        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);

        arrayPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(arrayPanel, java.awt.BorderLayout.CENTER);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        methods.set(Integer.parseInt(jTextField1.getText()));
        updateGui(Integer.parseInt(methods.get() + ""));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            methods.set(Integer.parseInt(jTextField1.getText()));
            updateGui(Integer.parseInt(methods.get() + ""));
        }
            
    }//GEN-LAST:event_jTextField1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private void updateGui(int i) {
        jTextField1.setText(i + "");
    }
}
