/*
 * MethodArrayModifier.java
 *
 * Created on October 27, 2008, 11:52 AM
 */
package draw;

import javax.swing.JToggleButton;

/**
 *
 * @author  nyffeldd
 */
public class MethodArrayModifier extends javax.swing.JPanel {

    private JToggleButton[] panelControllers;
    java.util.TreeSet<util.PaintableObjectAndMethodHolder> methods;
    Panel panel;

    /** Creates new form MethodArrayModifier */
    public MethodArrayModifier(java.util.TreeSet<util.PaintableObjectAndMethodHolder> methods, Panel p) {
        initComponents();
        this.methods = methods;
        this.panel = p;
        updateGui();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelControlPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jPanel2.add(jLabel1);

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jPanel2.add(jLabel2);

        jButton2.setText("Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Down");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jPanel2.add(jLabel3);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        panelControlPanel.setLayout(new java.awt.GridLayout(0, 1));

        jToggleButton1.setText("jToggleButton1");
        panelControlPanel.add(jToggleButton1);

        jScrollPane1.setViewportView(panelControlPanel);

        add(jScrollPane1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int index = -1;
        for (int i = 0; i < panelControllers.length; i++) {
            if (panelControllers[i].isSelected()) {
                index = i;
                break;
            }
        }

        if (index != -1) {
            for (util.PaintableObjectAndMethodHolder o : methods) {
                if (o.toString().equals(panelControllers[index].getText())) {
                    methods.remove(o);
                    break;
                }
            }
            updateGui();
            panel.rePrime();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = -1;
        for (int i = 0; i < panelControllers.length; i++) {
            if (panelControllers[i].isSelected()) {
                index = i;
                break;
            }
        }

        if (index - 1 > -1) {
            util.PaintableObjectAndMethodHolder prevO = null;
            for (util.PaintableObjectAndMethodHolder o : methods) {
                if (o.toString().equals(panelControllers[index].getText())) {
                    double temp = o.getRank();
                    o.setRank(prevO.getRank());
                    prevO.setRank(temp);
                    break;
                }
                prevO = o;
                updateGui();
                panel.rePrime();
                panelControllers[index - 1].setSelected(true);
            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = -1;
        for (int i = 0; i < panelControllers.length; i++) {
            if (panelControllers[i].isSelected()) {
                index = i;
                break;
            }
        }

        if (index + 1 < methods.size() && index != -1) {
            util.PaintableObjectAndMethodHolder prevO = null;
            boolean found = false;
            for (util.PaintableObjectAndMethodHolder o : methods) {
                if (o.toString().equals(panelControllers[index].getText())) {
                    found = true;
                } else if (found) {
                    double temp = o.getRank();
                    o.setRank(prevO.getRank());
                    prevO.setRank(temp);
                    break;
                }
                prevO = o;
                updateGui();
                panel.rePrime();
                panelControllers[index + 1].setSelected(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateGui() {
        jScrollPane1.setVisible(false);
        panelControlPanel.removeAll();
        panelControllers = new JToggleButton[methods.size()];
        int i = 0;
        for (util.PaintableObjectAndMethodHolder o : methods) {
            JToggleButton b = new JToggleButton(o.toString());
            b.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JToggleButton b = (JToggleButton) evt.getSource();
                    if (b.isSelected()) {
                        int index = 0;
                        for (int i = 0; i < panelControllers.length; i++) {
                            if (panelControllers[i] == b) {
                                index = i;
                            } else {
                                panelControllers[i].setSelected(false);
                            }
                        }
                    }
                }
            });
            panelControllers[i] = b;
            panelControlPanel.add(b);
            jScrollPane1.setVisible(true);
            i++;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panelControlPanel;
    // End of variables declaration//GEN-END:variables
}
