/*
 * IntArrayModifier.java
 *
 * Created on October 23, 2008, 12:43 PM
 */
package draw;

import util.GetAndSetMethodHolder;

/**
 *
 * @author  nyffeldd
 */
public class StringModifier extends javax.swing.JPanel {

    GetAndSetMethodHolder methods;

    /** Creates new form IntArrayModifier */
    public StringModifier(GetAndSetMethodHolder methods) {
        initComponents();
        this.methods = methods;
        updateGui(methods.get() + "");
        jTextField1.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        arrayPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1);

        arrayPanel.setLayout(new java.awt.BorderLayout());

        jTextField1.setColumns(5);
        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        arrayPanel.add(jTextField1, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(arrayPanel);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        methods.set(jTextField1.getText());
        updateGui(methods.get() + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            methods.set(jTextField1.getText());
            updateGui(methods.get() + "");
        }
            
    }//GEN-LAST:event_jTextField1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arrayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private void updateGui(String s) {
        jTextField1.setText(s);
    }
}
